# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ece65a6dc64cf279675d5f58053a01cb538707ce3079d1bcfc01661743611a64edb0aeef921ef62e2fa5dedba654ca90620ee4cff8084b0c07a5209711f33e8d

test:
  secret_key_base: b02f3349412222ae3d1628283294336d3c9ffda2d83c1b60c0d9d7db1f70fa53c42335ac7edeb364b3cdca82fd1e75bfb577738e127d9d9fdfd69e9da185e879

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
